image: google/dart:latest

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - packages/
    - web/packages/
    - .pub_cache/

stages:
  - build
  - test
  - publish

before_script:
  - export PUB_CACHE=$PWD/.pub_cache/
  - pub version
  - pub get
  - pub upgrade

analyze:
  stage: build
  script:
    - dartanalyzer lib example test    

test:
  stage: test
  script:
    - pub run test
  tags:
    - docker

# dry-run:
#  stage: publish
#  script:
#    - pub get
#    - pub publish --dry-run
#  only:
#    - master